#!/bin/sh
# check_load_simple <warn_1> <crit_1>
# Checks system load average. Returns perfdata.
WARN="${1:-5}"
CRIT="${2:-10}"

LOAD=$(uptime | sed -E 's/.*load averages?: //')
L1=$(echo "$LOAD" | awk -F'[, ]+' '{print $1}')
L5=$(echo "$LOAD" | awk -F'[, ]+' '{print $2}')
L15=$(echo "$LOAD" | awk -F'[, ]+' '{print $3}')

L1_INT=${L1%.*}
L1_INT=${L1_INT:-0}

if [ "$L1_INT" -ge "$CRIT" ]; then
  echo "LOAD CRITICAL - load average: ${L1}, ${L5}, ${L15} | load1=${L1};${WARN};${CRIT};0; load5=${L5};;;0; load15=${L15};;;0;"
  exit 2
elif [ "$L1_INT" -ge "$WARN" ]; then
  echo "LOAD WARNING - load average: ${L1}, ${L5}, ${L15} | load1=${L1};${WARN};${CRIT};0; load5=${L5};;;0; load15=${L15};;;0;"
  exit 1
else
  echo "LOAD OK - load average: ${L1}, ${L5}, ${L15} | load1=${L1};${WARN};${CRIT};0; load5=${L5};;;0; load15=${L15};;;0;"
  exit 0
fi
