package nrdp

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// writeGeneratedConfigLocked writes the current set of dynamic hosts/services
// to the configured cfg path as standard nagios `define host { ... }` /
// `define service { ... }` blocks.
//
// Why this exists:
//   - DynamicTracker creates objects in the in-memory store, but on gogios
//     restart only static .cfg files are loaded. retention.dat then attaches
//     state only to objects that already exist in the store, so every
//     NRDP-discovered host/service disappears for ~15 minutes until passive
//     check results trickle back in. Persisting the definitions to a file
//     that nagios loads via cfg_dir gives instant cross-restart fidelity.
//
// Atomicity: write to <path>.tmp then os.Rename. d.mu is assumed held by the
// caller; this is the only mutator of d.records and we read the store under
// d.store.Mu in EnsureHost / EnsureService.
//
// Cost: O(N) string formatting on every change. At our scale (hundreds of
// records) the alternative — batched flush — wins almost nothing and adds a
// startup-loss window if the daemon dies between flushes. Keep it simple.
func (d *DynamicTracker) writeGeneratedConfigLocked() {
	if d.cfgPath == "" {
		return
	}

	// Build sorted list of (host, service) keys for deterministic output.
	// Skip anything that already exists as a STATIC definition — emitting a
	// duplicate `define host { host_name=X }` makes nagios refuse to load
	// the whole config on startup ("duplicate host: X"), so we'd brick the
	// daemon. Static-vs-dynamic is determined by the store's Dynamic flag
	// (EnsureHost sets it true for objects it creates; objects loaded from
	// .cfg keep the zero value of false).
	//
	// IMPORTANT: callers (EnsureHost / EnsureService / Prune) hold
	// d.store.Mu (write lock) — do NOT acquire it here, that would deadlock.
	hosts := make([]string, 0)
	hostSet := make(map[string]struct{})
	type svcKey struct{ host, desc string }
	services := make([]svcKey, 0)

	for key := range d.records {
		if i := strings.Index(key, "\t"); i >= 0 {
			h, s := key[:i], key[i+1:]
			// Skip when this service is a static def. A static host can
			// legitimately host a dynamic service, so check the service
			// independently — not just the host.
			if ss := d.store.GetService(h, s); ss != nil && !ss.Dynamic {
				continue
			}
			services = append(services, svcKey{h, s})
			if _, ok := hostSet[h]; !ok {
				hostSet[h] = struct{}{}
				// Only emit the host stanza if it's dynamic (or doesn't
				// exist yet). For a dynamic service on a static host, we
				// need the service def but NOT the host def.
				if hh := d.store.GetHost(h); hh == nil || hh.Dynamic {
					hosts = append(hosts, h)
				}
			}
		} else {
			if hh := d.store.GetHost(key); hh != nil && !hh.Dynamic {
				continue
			}
			if _, ok := hostSet[key]; !ok {
				hostSet[key] = struct{}{}
				hosts = append(hosts, key)
			}
		}
	}

	sort.Strings(hosts)
	sort.Slice(services, func(i, j int) bool {
		if services[i].host != services[j].host {
			return services[i].host < services[j].host
		}
		return services[i].desc < services[j].desc
	})

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by gogios DynamicTracker. Do not edit by hand.\n")
	buf.WriteString("# Regenerated atomically on every NRDP host/service registration or prune.\n\n")

	for _, h := range hosts {
		fmt.Fprintf(&buf, "define host {\n")
		fmt.Fprintf(&buf, "    host_name               %s\n", h)
		fmt.Fprintf(&buf, "    alias                   %s\n", h)
		fmt.Fprintf(&buf, "    address                 %s\n", h)
		// max_check_attempts=1 + passive-only matches what NRDP submitters
		// expect: every passive result is authoritative, no soft-state
		// retries. Active checks are only enabled when SetHostCheckCommand
		// is called with a non-empty command name — many NRDP-discovered
		// hosts have NO DNS A record (fn2ai-east, fn2-prod-*) so running
		// fping against them returns "Invalid hostname/address" and flips
		// state DOWN even though passive results are landing fine.
		fmt.Fprintf(&buf, "    max_check_attempts      1\n")
		fmt.Fprintf(&buf, "    check_interval          5\n")
		fmt.Fprintf(&buf, "    retry_interval          1\n")
		fmt.Fprintf(&buf, "    check_period            24x7\n")
		if d.hostCheckCmd != "" {
			fmt.Fprintf(&buf, "    check_command           %s\n", d.hostCheckCmd)
			fmt.Fprintf(&buf, "    active_checks_enabled   1\n")
		} else {
			// No real check command configured — run check_dummy on the
			// normal interval so last_check stays fresh and the host shows
			// as UP. We can't use fping for many NRDP hosts (fn2-prod-*,
			// fn2ai-*) because their hostnames don't resolve, and dropping
			// active checks entirely leaves last_check pinned at registration
			// time (looks broken in the UI).
			fmt.Fprintf(&buf, "    check_command           check_dummy!0!OK\n")
			fmt.Fprintf(&buf, "    active_checks_enabled   1\n")
		}
		fmt.Fprintf(&buf, "    passive_checks_enabled  1\n")
		fmt.Fprintf(&buf, "    notifications_enabled   1\n")
		fmt.Fprintf(&buf, "    notification_period     24x7\n")
		fmt.Fprintf(&buf, "    notification_interval   120\n")
		fmt.Fprintf(&buf, "    notification_options    d,u,r\n")
		fmt.Fprintf(&buf, "    contact_groups          %s\n", d.contactGroupsCSV())
		fmt.Fprintf(&buf, "    retain_status_information      1\n")
		fmt.Fprintf(&buf, "    retain_nonstatus_information   1\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	for _, sv := range services {
		fmt.Fprintf(&buf, "define service {\n")
		fmt.Fprintf(&buf, "    host_name               %s\n", sv.host)
		fmt.Fprintf(&buf, "    service_description     %s\n", sv.desc)
		// check_dummy with rc=0 is the canonical passive-only placeholder
		// (matches what nrdp-micro emitted for these same services).
		fmt.Fprintf(&buf, "    check_command           check_dummy!0!OK\n")
		fmt.Fprintf(&buf, "    max_check_attempts      1\n")
		fmt.Fprintf(&buf, "    check_interval          5\n")
		fmt.Fprintf(&buf, "    retry_interval          1\n")
		fmt.Fprintf(&buf, "    check_period            24x7\n")
		fmt.Fprintf(&buf, "    active_checks_enabled   0\n")
		fmt.Fprintf(&buf, "    passive_checks_enabled  1\n")
		fmt.Fprintf(&buf, "    notifications_enabled   1\n")
		fmt.Fprintf(&buf, "    notification_period     24x7\n")
		fmt.Fprintf(&buf, "    notification_interval   60\n")
		fmt.Fprintf(&buf, "    notification_options    w,u,c,r\n")
		fmt.Fprintf(&buf, "    contact_groups          %s\n", d.contactGroupsCSV())
		fmt.Fprintf(&buf, "    retain_status_information      1\n")
		fmt.Fprintf(&buf, "    retain_nonstatus_information   1\n")
		fmt.Fprintf(&buf, "}\n\n")
	}

	if err := d.atomicWrite(buf.Bytes()); err != nil {
		d.logFunc("dynamic config writer: %v", err)
	}
}

// atomicWrite writes data to cfgPath via a sibling .tmp file + rename so a
// crashed/killed gogios cannot leave a half-written cfg that breaks the next
// nagios startup. Caller-supplied directory must exist; we MkdirAll once just
// in case (cheap if already there).
func (d *DynamicTracker) atomicWrite(data []byte) error {
	dir := filepath.Dir(d.cfgPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	tmp := d.cfgPath + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, d.cfgPath); err != nil {
		// Best-effort cleanup so we don't leak .tmp on rename failure.
		_ = os.Remove(tmp)
		return fmt.Errorf("rename %s -> %s: %w", tmp, d.cfgPath, err)
	}
	return nil
}

// contactGroupsCSV resolves the default contact groups (admins,
// discord-admins, bridge-admins) the same way EnsureHost does, but emits the
// names as a comma-separated string for the cfg file. Falls back to
// "bridge-admins" alone if none of the groups exist in the store yet, since
// at least one contact group is required for validation and bridge-admins is
// the always-present floor.
func (d *DynamicTracker) contactGroupsCSV() string {
	var names []string
	for _, name := range []string{"admins", "discord-admins", "bridge-admins"} {
		if cg := d.store.GetContactGroup(name); cg != nil {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return "bridge-admins"
	}
	return strings.Join(names, ",")
}
