package config

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/oceanplexian/gogios/internal/objects"
)

// generatedCfg mimics what DynamicTracker.writeGeneratedConfigLocked emits: a
// dynamic host, a good service on it, and an ORPHANED service whose host stanza
// was lost (the KANB-110 erosion bug). It must not brick the daemon, and the
// surviving objects must be flagged Dynamic so the tracker re-persists them.
const generatedCfg = `# Auto-generated by gogios DynamicTracker. Do not edit by hand.
define host {
    host_name               dyn-host
    alias                   dyn-host
    address                 dyn-host
    max_check_attempts      1
}

define service {
    host_name               dyn-host
    service_description     Good Svc
    check_command           check_dummy!0!OK
    max_check_attempts      1
}

define service {
    host_name               missing-host
    service_description     Orphan Svc
    check_command           check_dummy!0!OK
    max_check_attempts      1
}
`

func parseGenerated(t *testing.T) (*ObjectParser, string) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "nrdp_generated.cfg")
	if err := os.WriteFile(path, []byte(generatedCfg), 0644); err != nil {
		t.Fatalf("write cfg: %v", err)
	}
	parser := NewObjectParser()
	if err := parser.ParseFile(path); err != nil {
		t.Fatalf("ParseFile: %v", err)
	}
	return parser, path
}

// When the file is recognized as the NRDP-generated cfg, an orphaned service is
// dropped (load succeeds) and surviving host/service are flagged Dynamic.
func TestExpand_GeneratedCfg_DropsOrphanAndFlagsDynamic(t *testing.T) {
	parser, path := parseGenerated(t)
	store := objects.NewObjectStore()

	if err := ExpandAndRegister(parser, store, path); err != nil {
		t.Fatalf("expected orphaned dynamic service to be skipped, got fatal: %v", err)
	}

	h := store.GetHost("dyn-host")
	if h == nil {
		t.Fatal("dyn-host should have been registered")
	}
	if !h.Dynamic {
		t.Error("host from generated cfg should be flagged Dynamic so the tracker re-persists it")
	}

	good := store.GetService("dyn-host", "Good Svc")
	if good == nil {
		t.Fatal("Good Svc should have been registered")
	}
	if !good.Dynamic {
		t.Error("service from generated cfg should be flagged Dynamic")
	}

	if orphan := store.GetService("missing-host", "Orphan Svc"); orphan != nil {
		t.Error("orphaned service on missing host should have been dropped, not registered")
	}
}

// The same orphan in a normal static config is a hard error — we only relax for
// the regenerable generated cfg.
func TestExpand_StaticCfg_OrphanIsFatal(t *testing.T) {
	parser, _ := parseGenerated(t)
	store := objects.NewObjectStore()

	// genCfgFile = "" (or any non-matching path) => strict.
	if err := ExpandAndRegister(parser, store, ""); err == nil {
		t.Fatal("expected orphaned service in a static config to be a fatal error")
	}
}

// A non-matching genCfgFile path must not flag unrelated objects Dynamic.
func TestExpand_NonGeneratedCfg_NotFlaggedDynamic(t *testing.T) {
	parser, path := parseGenerated(t)
	store := objects.NewObjectStore()

	// Point genCfgFile at a different file so these objects are treated static;
	// the orphan then makes the load fail, which is fine — we only assert the
	// flag semantics on a fresh, orphan-free store below.
	_ = path
	other := filepath.Join(t.TempDir(), "somewhere-else.cfg")
	if err := ExpandAndRegister(parser, store, other); err == nil {
		t.Fatal("orphan should be fatal when file is not the generated cfg")
	}
}
